GET http://api.bybit.com/public/linear/kline
        ?symbol=ETHUSDT
        &interval=1
        &limit=3
        &from=1585118245

###
GET http://sugang.ajou.ac.kr/aply/index.action


###
GET https://api.bybit.com/v2/public/tickers?symbol=BTCUSDT
