GET http://api.bybit.com/public/linear/kline
        ?symbol=BTCUSDT
        &interval=1
        &limit=100
        &from=1613459531

###
GET http://sugang.ajou.ac.kr/aply/index.action


###
GET https://api.bybit.com/v2/public/tickers?symbol=BTCUSDT
